name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
# taken from https://swimburger.net/blog/dotnet/fix-blazor-webassembly-pwa-integrity-checks
on:
    push:
        branches: [ develop ]

defaults:
    run:
        working-directory: src/GlobApp
jobs:
    deploy-to-github-pages:
        # use ubuntu-latest image to run steps on
        runs-on: ubuntu-latest
        steps:
            # uses GitHub's checkout action to checkout code form the master branch
            - uses: actions/checkout@v2

            # sets up .NET 6
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.13

            # publishes Blazor project to the release-folder
            - name: Publish .NET Core Project
              run: dotnet publish GlobApp.csproj -c Release -o release --nologo

            # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: src/GlobApp/release/wwwroot
